# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='blog.date')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='blog.image')),
                ('title', models.CharField(max_length=50, verbose_name='blog.title')),
                ('description', models.TextField(verbose_name='blog.text')),
            ],
        ),
    ]
